/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Nihilai Collective Corp
 * https://github.com/nihilai-collective/jsonifier
 * include/jsonifier-incl/core/backend_pass_reset.hpp
 */

#undef JSONIFIER_PASS_GUARD_SIMD_CONFIG
#undef JSONIFIER_PASS_GUARD_AVX
#undef JSONIFIER_PASS_GUARD_NEON
#undef JSONIFIER_PASS_GUARD_SVE2
#undef JSONIFIER_PASS_GUARD_FALLBACK
#undef JSONIFIER_PASS_GUARD_AVX_STAGE1
#undef JSONIFIER_PASS_GUARD_NEON_STAGE1
#undef JSONIFIER_PASS_GUARD_SVE2_STAGE1
#undef JSONIFIER_PASS_GUARD_ADD_TAPE_VALUES
#undef JSONIFIER_PASS_GUARD_UTF8_VALIDATION
#undef JSONIFIER_PASS_GUARD_COMPARE
#undef JSONIFIER_PASS_GUARD_HASH_MAP
#undef JSONIFIER_PASS_GUARD_UTILITIES_SIMD
#undef JSONIFIER_PASS_GUARD_STRING_UTILS
#undef JSONIFIER_PASS_GUARD_JSON_ITERATOR
#undef JSONIFIER_PASS_GUARD_VALIDATOR
#undef JSONIFIER_PASS_GUARD_PARSER
#undef JSONIFIER_PASS_GUARD_NUMBER_UTILS
#undef JSONIFIER_PASS_GUARD_SERIALIZER
#undef JSONIFIER_PASS_GUARD_PARSE_IMPL
#undef JSONIFIER_PASS_GUARD_SERIALIZE_IMPL
#undef JSONIFIER_PASS_GUARD_MINIFIER
#undef JSONIFIER_PASS_GUARD_PRETTIFIER
#undef JSONIFIER_PASS_GUARD_GENERIC_ITERATOR
